subplot(2,1,1)
plot(uout(1:10:end),ubarout(1:10:end),'.')
xlabel('input')
ylabel('output')
legend('static nonlinear function')
subplot(2,1,2)
plot(ubarout(1:10:end),xbarout(1:10:end),'.')
xlabel('input')
ylabel('output')
legend('dynamic linear function')